# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: C22037

on:
  push:
    branches: [ "DevOps_C22037" ]
  pull_request:
    branches: [ "DevOps_C22037" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: |
        cd C22037\Dokcer
        dotnet restore
    - name: Build
      run: |
        cd C22037\Dokcer
        dotnet build --no-restore
    - name: Test
      run: |
        cd C22037\Dokcer
        dotnet test --no-build --verbosity normal
